package com.example.ashasaathi

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.ashasaathi.ui.theme.*

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun OfficialReportScreen(viewModel: MainViewModel, onBack: () -> Unit) {
    val context = androidx.compose.ui.platform.LocalContext.current
    val report by viewModel.monthlyReport.collectAsState()
    val patients by viewModel.patients.collectAsState()
    val alerts by viewModel.alerts.collectAsState()
    
    fun shareReport() {
        val reportText = StringBuilder().apply {
            append("OFFICIAL GOVERNMENT HEALTH REPORT\n")
            append("==================================\n")
            append("Village: ${viewModel.userName.value}'s Jurisdiction\n")
            append("Date: ${java.text.SimpleDateFormat("dd-MM-yyyy").format(java.util.Date())}\n\n")
            append("SUMMARY:\n")
            append("- Total Patients Registered: ${patients.size}\n")
            append("- Critical Alerts Triggered: ${alerts.size}\n\n")
            append("PATIENT LEDGER:\n")
            patients.forEach { append("- ${it.name} (${it.type}) [${it.status}]\n") }
            append("\nALERT HISTORY:\n")
            alerts.forEach { append("! ${it.patientName}: ${it.riskFactor} (${it.timestamp})\n") }
            append("\n==================================\n")
            append("Generated by ASHA Saathi Digital Assistant")
        }.toString()

        val intent = android.content.Intent(android.content.Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(android.content.Intent.EXTRA_SUBJECT, "Government Health Report")
            putExtra(android.content.Intent.EXTRA_TEXT, reportText)
        }
        context.startActivity(android.content.Intent.createChooser(intent, "Share Official Report"))
    }

    LaunchedEffect(Unit) {
        viewModel.fetchPatients(isDoctor = true)
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Government Health Report", color = SurfaceWhite, fontWeight = FontWeight.Bold) },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.Default.ArrowBack, contentDescription = "Back", tint = SurfaceWhite)
                    }
                },
                actions = {
                    IconButton(onClick = { shareReport() }) {
                        Icon(Icons.Default.KeyboardArrowDown, contentDescription = "Download", tint = SurfaceWhite)
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(containerColor = PrimaryGreen)
            )
        }
    ) { paddingValues ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(paddingValues)
                .background(BackgroundLight)
                .padding(16.dp)
        ) {
            // Stats Overview
            Card(
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(containerColor = SurfaceWhite),
                shape = RoundedCornerShape(12.dp),
                elevation = CardDefaults.cardElevation(2.dp)
            ) {
                Column(modifier = Modifier.padding(16.dp)) {
                    Text("Village Statistics", fontWeight = FontWeight.Bold, color = SecondaryBlue)
                    Spacer(modifier = Modifier.height(8.dp))
                    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                        StatItem("Patients", patients.size.toString(), PrimaryGreen)
                        StatItem("Alerts", alerts.size.toString(), AccentRed)
                        StatItem("Month", "April", SecondaryBlue)
                    }
                }
            }
            
            Spacer(modifier = Modifier.height(24.dp))
            Text("Patient & Alert Records", fontSize = 18.sp, fontWeight = FontWeight.Bold, color = TextDark)
            Spacer(modifier = Modifier.height(8.dp))
            
            // Record List
            Card(
                modifier = Modifier.fillMaxWidth().weight(1f),
                colors = CardDefaults.cardColors(containerColor = SurfaceWhite),
                shape = RoundedCornerShape(12.dp),
                elevation = CardDefaults.cardElevation(2.dp)
            ) {
                if (patients.isEmpty() && alerts.isEmpty()) {
                    Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
                        Text("No official records yet", color = TextMuted)
                    }
                } else {
                    LazyColumn(modifier = Modifier.fillMaxSize()) {
                        item {
                            Text("Village Registrations", modifier = Modifier.padding(16.dp), fontWeight = FontWeight.Bold, color = PrimaryGreen)
                        }
                        items(patients) { patient ->
                            ListItem(
                                headlineContent = { Text(patient.name, fontWeight = FontWeight.Bold) },
                                supportingContent = { Text("${patient.type} • Village Area") },
                                trailingContent = { 
                                    val isSynced = patient.status == "Synced"
                                    Text(
                                        text = patient.status, 
                                        color = if(isSynced) PrimaryGreen else WarningOrange, 
                                        fontWeight = FontWeight.Bold,
                                        fontSize = 12.sp
                                    ) 
                                },
                                leadingContent = { Icon(Icons.Default.Person, contentDescription = null, tint = PrimaryGreen) }
                            )
                            Divider(modifier = Modifier.padding(horizontal = 16.dp), color = BackgroundLight)
                        }
                        
                        item {
                            Spacer(modifier = Modifier.height(16.dp))
                            Text("Health Alert History", modifier = Modifier.padding(16.dp), fontWeight = FontWeight.Bold, color = AccentRed)
                        }
                        items(alerts) { alert ->
                            ListItem(
                                headlineContent = { Text(alert.patientName, fontWeight = FontWeight.Bold) },
                                supportingContent = { Text(alert.riskFactor) },
                                trailingContent = { Text(alert.timestamp, fontSize = 11.sp, color = TextMuted) },
                                leadingContent = { Icon(Icons.Default.Warning, contentDescription = null, tint = AccentRed) }
                            )
                            Divider(modifier = Modifier.padding(horizontal = 16.dp), color = BackgroundLight)
                        }
                    }
                }
            }
            
            Spacer(modifier = Modifier.height(16.dp))
            Button(
                onClick = { shareReport() },
                modifier = Modifier.fillMaxWidth().height(56.dp),
                colors = ButtonDefaults.buttonColors(containerColor = PrimaryGreen),
                shape = RoundedCornerShape(12.dp)
            ) {
                Icon(Icons.Default.KeyboardArrowDown, contentDescription = null)
                Spacer(modifier = Modifier.width(8.dp))
                Text("Download Official Health Report", fontWeight = FontWeight.Bold)
            }
        }
    }
}

@Composable
fun StatItem(label: String, value: String, color: Color) {
    Column(horizontalAlignment = Alignment.CenterHorizontally) {
        Text(value, fontSize = 20.sp, fontWeight = FontWeight.Bold, color = color)
        Text(label, fontSize = 11.sp, color = TextMuted)
    }
}
